[tools]
# Default dart-sass version to download.
sass = "1.97.1"
# Default wasm-bindgen version to download.
wasm_bindgen = "0.2.106"
# Default wasm-opt version to download.
wasm_opt = "version_125"
# Default tailwindcss-cli version to download.
tailwindcss = "4.1.18"

